export const site_logo = "#nava";
export const site_carousel = ".carousel-inner";
export const site_navbar = "#navbarExample";
export const category_list = ".list-group";
export const products_container = "#tbodyid";
export const footer_container = "#footc";
export const footer_about_us = "//div[@id='fotcont']/div[1]";
export const footer_get_in_touch = "//div[@id='fotcont']/div[2]";
export const footer_logo = "//div[@id='fotcont']/div[3]";
